language: python
python:
  - "3.5"
install:
  - pip install --upgrade pip #[他預先的 pip 版本不是最新的，所以先更新一下]
  - pip install -r requirements.txt

notifications:
  email:
    recipients:
      - john987john987@gmail.com
    on_success: always
    on_failure: always